export const LESSONS_DATA = [
    {
        id: 0,  
        date: new Date(2024, 0, 28, 18),
        lesson: 'Физика',
        name: 'Савва',
        place: '',
        isOnline: true,
    },
    {
        id: 1,
        date: new Date(2024, 0, 26, 20),
        lesson: 'Математика',
        name: 'Леня',
        place: '',
        isOnline: true,
    },
    {   
        id: 2,
        date: new Date(2024, 1, 2, 17),
        lesson: 'Математика',
        name: 'Даня',
        place: 'М университет',
        isOnline: false,
    },
    {
        id: 3,
        date: new Date(2024, 0, 28, 18),
        lesson: 'Физика',
        name: 'Савва',
        place: 'М черепашья нора',
        isOnline: false,
    },
    {
        id: 4,
        date: new Date(2024, 0, 26, 20),
        lesson: 'Математика',
        name: 'Леня',
        place: 'М черепашья нора',
        isOnline: false,
    },
    {
        id: 5,
        date: new Date(2024, 1, 2, 17),
        lesson: 'Математика',
        name: 'Даня',
        place: 'М университет',
        isOnline: false,
    },
    {
        id: 6,
        date: new Date(2024, 0, 28, 18),
        lesson: 'Физика',
        name: 'Савва',
        place: 'М черепашья нора',
        isOnline: false,
    },
    {
        id: 7,
        date: new Date(2024, 0, 26, 20),
        lesson: 'Математика',
        name: 'Леня',
        place: 'М черепашья нора',
        isOnline: false,
    },
    {
        id: 8,
        date: new Date(2024, 1, 2, 17),
        lesson: 'Математика',
        name: 'Даня',
        place: 'М университет',
        isOnline: false,
    },
    {
        id: 9,
        date: new Date(2024, 0, 28, 18),
        lesson: 'Физика',
        name: 'Савва',
        place: 'М университет',
        isOnline: false,
    },
    {
        id: 10,
        date: new Date(2024, 0, 26, 20),
        lesson: 'Математика',
        name: 'Леня',
        place: 'М черепашья нора',
        isOnline: false,
    },
    {
        id: 11,
        date: new Date(2024, 1, 2, 17),
        lesson: 'Математика',
        name: 'Даня',
        place: 'М черепашья нора',
        isOnline: false,
    },]
